pubsub:
  type: "nats"
  config:
    url: "nats://localhost:4222"
proxy:
  url: "http://localhost:8080" # This should be the address the connector uses to reach this instance.
openai:
  default_app_id: "ollama"
  default_user_id: "openai-user"
