// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/tunnel/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelMessage wraps either a request or response flowing through the tunnel.
type TunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier to correlate requests with responses.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelMessage_HttpRequest
	//	*TunnelMessage_HttpResponse
	Payload       isTunnelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_pkg_tunnel_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TunnelMessage) GetPayload() isTunnelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelMessage) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *TunnelMessage) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

type isTunnelMessage_Payload interface {
	isTunnelMessage_Payload()
}

type TunnelMessage_HttpRequest struct {
	// An ADK HTTP request forwarded from the Router Proxy to the Connector.
	HttpRequest *HttpRequest `protobuf:"bytes,2,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type TunnelMessage_HttpResponse struct {
	// An ADK HTTP response returned from the Connector to the Router Proxy.
	HttpResponse *HttpResponse `protobuf:"bytes,3,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

func (*TunnelMessage_HttpRequest) isTunnelMessage_Payload() {}

func (*TunnelMessage_HttpResponse) isTunnelMessage_Payload() {}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_pkg_tunnel_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_pkg_tunnel_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_pkg_tunnel_tunnel_proto protoreflect.FileDescriptor

const file_pkg_tunnel_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/tunnel/tunnel.proto\x12\x06tunnel\"\xb0\x01\n" +
	"\rTunnelMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\fhttp_request\x18\x02 \x01(\v2\x13.tunnel.HttpRequestH\x00R\vhttpRequest\x12;\n" +
	"\rhttp_response\x18\x03 \x01(\v2\x14.tunnel.HttpResponseH\x00R\fhttpResponseB\t\n" +
	"\apayload\"\xc5\x01\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12:\n" +
	"\aheaders\x18\x03 \x03(\v2 .tunnel.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12;\n" +
	"\aheaders\x18\x02 \x03(\v2!.tunnel.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012L\n" +
	"\rTunnelService\x12;\n" +
	"\aConnect\x12\x15.tunnel.TunnelMessage\x1a\x15.tunnel.TunnelMessage(\x010\x01B/Z-github.com/innomon/adk-cloud-proxy/pkg/tunnelb\x06proto3"

var (
	file_pkg_tunnel_tunnel_proto_rawDescOnce sync.Once
	file_pkg_tunnel_tunnel_proto_rawDescData []byte
)

func file_pkg_tunnel_tunnel_proto_rawDescGZIP() []byte {
	file_pkg_tunnel_tunnel_proto_rawDescOnce.Do(func() {
		file_pkg_tunnel_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tunnel_tunnel_proto_rawDesc), len(file_pkg_tunnel_tunnel_proto_rawDesc)))
	})
	return file_pkg_tunnel_tunnel_proto_rawDescData
}

var file_pkg_tunnel_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_tunnel_tunnel_proto_goTypes = []any{
	(*TunnelMessage)(nil), // 0: tunnel.TunnelMessage
	(*HttpRequest)(nil),   // 1: tunnel.HttpRequest
	(*HttpResponse)(nil),  // 2: tunnel.HttpResponse
	nil,                   // 3: tunnel.HttpRequest.HeadersEntry
	nil,                   // 4: tunnel.HttpResponse.HeadersEntry
}
var file_pkg_tunnel_tunnel_proto_depIdxs = []int32{
	1, // 0: tunnel.TunnelMessage.http_request:type_name -> tunnel.HttpRequest
	2, // 1: tunnel.TunnelMessage.http_response:type_name -> tunnel.HttpResponse
	3, // 2: tunnel.HttpRequest.headers:type_name -> tunnel.HttpRequest.HeadersEntry
	4, // 3: tunnel.HttpResponse.headers:type_name -> tunnel.HttpResponse.HeadersEntry
	0, // 4: tunnel.TunnelService.Connect:input_type -> tunnel.TunnelMessage
	0, // 5: tunnel.TunnelService.Connect:output_type -> tunnel.TunnelMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_tunnel_tunnel_proto_init() }
func file_pkg_tunnel_tunnel_proto_init() {
	if File_pkg_tunnel_tunnel_proto != nil {
		return
	}
	file_pkg_tunnel_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_HttpRequest)(nil),
		(*TunnelMessage_HttpResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tunnel_tunnel_proto_rawDesc), len(file_pkg_tunnel_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_tunnel_tunnel_proto_goTypes,
		DependencyIndexes: file_pkg_tunnel_tunnel_proto_depIdxs,
		MessageInfos:      file_pkg_tunnel_tunnel_proto_msgTypes,
	}.Build()
	File_pkg_tunnel_tunnel_proto = out.File
	file_pkg_tunnel_tunnel_proto_goTypes = nil
	file_pkg_tunnel_tunnel_proto_depIdxs = nil
}
